server:
  port: 8040
spring:
  application:
    ### 服务名称
    name: shop-service
  boot:
    admin:
      url: http://localhost:8900

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false