spring:
  profiles:
    active: dev

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 9000

ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000